name: Publish VS Code Extension

on:
  push:
    tags:
      - 'stryker-mutator@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: marketplace
    permissions: # Allow the workflow to request tokens
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Publish prerelease to VS Code Marketplace (non-main branches)
        if: ${{ github.ref != 'refs/heads/main' }}
        run: npm run deploy:prerelease
        working-directory: packages/vscode-plugin

      - name: Publish to VS Code Marketplace (main branch)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm run deploy
        working-directory: packages/vscode-plugin
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
